### ISSUE TITLE
inaccurate narrative

### ISSUE THREAD

**Issue by mgavish** [learn-co-curriculum/dsc-2-14-12-gradient-descent-step-sizes-lab#4]
"In this lab, we'll practice applying gradient descent. As we know gradient descent begins with an initial regression line, and moves to a "best fit" regression line by changing values of  𝑚  and  𝑏  and evaluating the RSS. So far, we have illustrated this technique by changing the values of  𝑏  and evaluating the RSS. In this lab, we will work through applying our technique by changing the value of  𝑚  instead. Let's get started."

we have been changing values of m so far and in this lab, we work on changing values of b, narrative above has it reversed.

**Comment by fpolchow** [comment]
You are correct. We've gotten this fixed. Thank you for flagging!
